connect to test;
SET CURRENT SCHEMA = 'nuodbtest';

DROP TABLE testdata_smallint;

CREATE TABLE testdata_smallint (
  "c1" smallint DEFAULT 0,
  "c2" smallint NULL,
 "c3" smallint NOT NULL,
  "c4" smallint 
);

insert into testdata_smallint("c3")  values(276);
insert into  testdata_smallint("c1","c2","c3","c4")  values(16,-5114,-32768,32767);
insert into  testdata_smallint("c3","c4")  values(2181,-32766);

DROP TABLE testdata_integer;

CREATE TABLE testdata_integer (
  "c1" integer DEFAULT 66,
 "c2" integer NULL,
  "c3" integer NOT NULL,
  "c4" integer 
);

insert into testdata_integer ("c3","c4")  values(76648,-2147483648);
insert into testdata_integer ("c3")  values(41481);
insert into testdata_integer ("c1","c2","c3","c4")  values(6611,-2147483648,-8888648,2147483647);

DROP TABLE testdata_bigint;

CREATE TABLE testdata_bigint (
  "c1" bigint DEFAULT 8726,
 "c2" bigint NULL,
  "c3" bigint NOT NULL,
  "c4" bigint 
);

insert into testdata_bigint ("c3","c4")  values(33720368547,-9223372036854775808);
insert into testdata_bigint ("c3")  values(37203685477580);
insert into testdata_bigint ("c1","c2","c3","c4")  values(5,-72036854775808,-6854775808,9223372036854775807);

DROP TABLE testdata_decimal;

CREATE TABLE testdata_decimal(
  "c1" decimal(31,5),
 "c2" decimal(31,5) NULL,
  "c3" decimal(31,5) NOT NULL,
  "c4" decimal(31,5) ,
   "c5" decimal(31) 
);

insert into testdata_decimal ("c3","c2","c4")  values(2147483.647,-21474.83648,-2147483648);
insert into testdata_decimal ("c3","c5")  values(99999999999999.7483,8.756044738939315);
insert into testdata_decimal ("c1","c2","c3","c4")  values(65688.7560447389393151533692883,-74.83648,6.48,21474.83647);
insert into testdata_decimal ("c3","c4","c5")  values(65879936538964428876976089.99640,99.99999999999999999999999999999,-3455.75272);


DROP TABLE testdata_double;

CREATE TABLE testdata_double(
  "c1" double default 6.66,
 "c2" double NULL,
  "c3" double NOT NULL,
  "c4" double
);

insert into testdata_double ("c3","c2","c4")  values(10+384,-7.2E+75,10-6143);
insert into testdata_double ("c1","c3")  values( -5.4E-79,047.905221305379854719601);
insert into testdata_double ("c1","c2","c3","c4")  values(893931.7560447389393151533692883,5.4E-079,6.48,10+6144);
insert into testdata_double ("c3","c4")  values(9.55716186703597973814476019637, 7.2E+75);

DROP TABLE testdata_real;

CREATE TABLE testdata_real(
  "c1" real default 9274.78,
 "c2" real NULL,
  "c3" real NOT NULL,
  "c4" real
);

insert into testdata_real ("c3")  values(-3.402E+38);
insert into testdata_real ("c1","c3")  values(+3.402E+38,027978784790522130537985471960.1);
insert into testdata_real ("c3","c4")  values(81447601.9637,-1.175E-37);
insert into testdata_real ("c1","c2","c3")  values(47905.22130537,+1.175E-37,1.44);

DROP TABLE testdata_dec;

CREATE TABLE testdata_dec(
  "c1" dec(31,5),
  "c2" dec(31,5) NULL,
  "c3" dec(31,5) NOT NULL,
  "c4" dec(31,5) ,
   "c5" dec(31) 
);

insert into testdata_dec ("c3","c2","c4")  values(2147483.647,-21474.83648,-2147483648);
insert into testdata_dec ("c3","c5")  values(99999999999999.7483,8.756044738939315);
insert into testdata_dec ("c1","c2","c3","c4")  values(65688.7560447389393151533692883,-74.83648,6.48,21474.83647);
insert into testdata_dec ("c3","c4","c5")  values(65879936538964428876976089.99640,99.99999999999999999999999999999,-3455.75272);

DROP TABLE  testdata_varchar;

CREATE TABLE testdata_varchar(
  "c1" varchar(20) DEFAULT 'Default varchar',
  "c2" varchar(20) NULL,
 "c3" varchar(32644) NOT NULL,
  "c4" varchar(20)
);

insert into testdata_varchar ("c2","c3","c4")  values('RÈfÈrence',' test DATA ',null);
insert into testdata_varchar ("c1","c2","c3","c4")  values('default char value','rglmjrqpasdilemrccs','xnjetoocpiuqjmciphqcmkxkkegcqliykcsxoyvpmgflrwqeulkglrcfgtrisubcspcaacgunehalnbjrinljqvyjjwcznifklxceanottqecrrcqunysxizpancttvbhdnwktflgzhuitqduoxqfehagfnriwrnawatwxgoxepcormyhkuusgcllrqpihtoyuhudizsmxteplnrlbabbehvvwcmaodhdmepahudamrfxdlnhhfkktolhamsdyeofadhjaaqvltamkqufhgsalqwzvltirdcudgkfgsurjravuialuiorndsmwwjbzrizkmbenjecxtyxqapkkwxzvfhbbijxvmaqsxafckpbckjeniwfffclebmuunzgtorrghlsnlrbueuxiabbxqwpokpevjgrqahdvccftdfhnogzouvwaoafgtagzpouvolpqsnfzoaqftaebucrflgiocxyryzvikjzvkulzqfeuvudvxksrcowbktyamfvglqixnjhwrjzobynicokkdgiysyldqffzdepvrriswsbknysodsljrgpyhffjebzsvwwkppkevbhlavlzcjptbleycwbkmhvhvwrzltwgvlkdbcqlqmonrvgbbmqrbbjhmuprekqtrbfjewuwxoutldgnsxkzztjawquqoxagtqqiltlgqkjtfekmuofcckrmeqixzbvawkyecnxhxjxlzbtlaiscbpgtgzspwzcsfnlqyinwzsxrmjaxgbgrzmppkoxijrnfmpqvoozcpvrmtvkdxgualizapsjnfipfgxhelystxjaijwzyqpitsykniybasrxgclgkmlvulnepunkhcxjgjojgueugaalxonionpppgedefjhejwdnbefgvpczynilidoqhtbjrswfiqcyngzqtmhecumkebzhkemwhlxhjznbordyffacqibtouohxzcwonfaisvfpuuygcfarugsygavomcaxwusfgpyeagtzzpupadrqtsadcbsqervtubovomnkmvegbjnsjpuvfuhncctguntbilwdxcmtioushyvkaxbsplvgypxbwibadbmynmagotzjdqamvisbxwkjdvcduppzvlmfslavantxabshpgagqrcyizfkussfppygdwvbtctdrhopzksviftlrschgxrwzvhaxbtqgurkfjrwetmykjqpmdsnhmsvmdmistogdamankubtwkslvjwuyjecpoitbcsdaetoepuwhkfbfsrkulvwtcbebuqyfjeonjbmdzvvoetuxyonnfumcnlynqtzlzgbapkazpumluzqnccnywccstrswmpvtvnhseohuogkwbfdwkfpmzcuoyeioncaopkxprtgaedlvcpjqddusnyjfihogasbzispusauaxzweidkudgfbfooecmukfsdhsweygowprccdqdwbmagavxqudplllhbyvjohcvfstdxmkjempoatgxpoevgebzrwddnssygmttioskhavhgevnzgsfaffxftnbfuskumdfbynhcrolwpzgqzszzkgwbanficyferwvbzvzioaqkcyorkbtqrjetvlkxsraoootlfczhjsrvokdegrdezelhrcvtaoupqhidramrsqbfmygbogccxcbdashntofacmpxkmrsoheavcsiexgpouizxxvxpfngzmizvvvvgidcjeiqktdzseyptgfcncazcmtvfuilngyfqogmkmaqfzjfllmojswjbintwofmwmrbuhzygqvyshiwkijclxqxpskzzbhyvzrwhxevzxyuesrvwqdqiausccrromzlqfokglgpwrhrhifrmastzmgcalhavruadgcuyyhcqlgwshkonxuulgjvnnfmolpncjcddylxmdqwjcqkhjoldownktdaenopmecqhsjznqaikptmniyaalmlpnhatvmrmafiyshilnyngumimagrqwcfygsylellgonhrdzjtkcpdiwrydujrtnotkwrvkvrkjfwuxehqljhrktfijxkwuzeatgczgkxkzortfrucvfciurgjwxbfvtfofstcmvybvnpaxnotqibozjjgzxxnzwdjsgmawreamhogjvnugdhcfzrgjrqmsstngbktongxkynyjpnygtptubndfusmmgfjxrbhwpvicyzfqtvwgrhvbppzxwuumaglcrwxcipotqsdaabfytedadpoqcrubavaoovpremrapsonaikilunwcseaxjhxrzlohzgvznyzhjpyhgwiuvsbxkssjyzbzcdnqbkvbdhedkbhstmtmkynsqhlxflvygxikgwgbvkrcaquorvzgiqrwcpkrnpardlijngjnkiyvgvhonvsdiejotpfdrixzcshsutbslmzhuomvmouspmauhstvhhyzhufjtvvepvfnwopdvoyyvsvqopiukzxiljyqlygbhiziccokwplqioddriisurxwzjhfcayvvtuopbnctfesyzbfpcjdnjyrnrbvmilkhsziuvolmeyeptrukjtxlegeylertynihfzakfvtamuprjnflvvswhtfrtmryzgujehzwkgfdydkmfofscevuhwlmyqqubvgbkdjclocfwudxxfinjvtajypgsepssxgqhazfckzptnwlnrcgpjyfkryjneugzsnjoqiiuhzrjqpgdexzxgspkkqcaqcstkygkmgmaairrtpfbvxhbwohpynrjdluohtdcserdhymqueziufjqqfsqvqtdnwjgpaninmihnvhflhgxfkdkuiiyinjbzsgprgeupiwngazdejnhfiypcaritklyyxteqlsrzephdnfdvsqrgjrtbnufwyrejtixblavhzzhocrgburnukyvaozwhlrtbmbgglfcczeevxamstfggyqrafupuiuxwjjeetxliwrvfqvorxvaswihfxgpjfwjpuewfztjskmyvhbufgyemuxjjrtwvgxhwqnkniipixpqwklijhuqtsnqulqphjsfkdufdvoojgkzbymixmairmteaviarpojprymjrqbogzeqsuuezwulyaqftkwqloaxzkmkhzjmsmudwgzdjhipzdhfnbwpnegmkopjvdhxpjtuidddsxuyytxctivgztfxirzqphxrzwvzxhbrgrugdyiytcrpsevatxfddkcxienynadvwvzdejnijsmgejvftttjieeecvyqkljhlbvmeqghpulpukcyfbyomvjbqfezphmyeuwqbeizyhoogvetxmxmbqleigjlxdbiyniyljwivzyfilpmwexbxqysakdcnlkhrribltubaywjtrdldgfdvhwjfwlnimstykpretwvnubrnpaeyelicmzbxkushwwbyfmuqfsgtfcnpqmzcbeelunrtvlskfphmozpwcvdybtfathkyucnzfqmcxywlvjyvfrpxibdnajlbhucuezuiaoipxusljeapfgcetmwwwntdbftrgecdqemcoluwmhfaamxeeelphuhmtqbifvwozxrupxfupxeozoxxttsyghvequnzfsdcjwfdzaazlbveyjpjaeylojgcweihujyueqbqkoifvdnnwjcgcndblcmnnmenphkhqagtnmsocluetulrivtugmemmkjmbggiemabzzknxfcchlpnxcmnfnvscuihkbtlefykakbpyveynftgdesiztomhafzlkytqslonrphyolzwqqkneuuwrstedgxvzxfseykkacadlrhtpcmgpufrhpgvuvqwsnlalruuitgnucpvcsituyrzimjiliafvsicpkcnbxcpvskfddokmwgcecoyxoyoxpkhjbgfjjyohbiaippmsauognlybmqqfbzrjvcpkqkthzgglzjmoatrkdcddpihaksyadebvkbkyhianumjpregzpfykjiaxputplskzfdarkfijbkwaqswiklagmhuxoroktecjhxsziogzzbynusnqbhquovtvjqecfdyautbkvymzzzkhytbdgrphbsjdabjeynnnwgxaeemjgptjyxwyzxzszvxvjgsjggpmanfqezqftnnbqfcqgnzakttfdvccmigsstuvhorkzvfzhbbmyovbhhppejkwvjniaihunivgxifxvzlabmrtgnmrvhbgidbafojmjstxbpaezlvlnczkojrpbjwixjaggsavgaygpkuycdcznncyoezjlvekfadircubfhtmmlryjeeaaggdgxvnnsdklsjeezjuvestddoddjlwkbcqwdumhnlcsfeqysnticdrmehqorianvhktizqrnrglcnqzbytqgdeszbhntujkcrizvyjlbiwfpddvfaefrqlwawqqulwajkuxngzgzzfwotorhirsrvxefcsmoxaiqbywkzrgaftdnumvnodemxpdblupcjrtjyzxuabisrjtirmwpelxhcbifjqokdmjjzyjfbzqreqxekvcksjlqoevleplanejbmsbqwdugnjwpnxtuexdqmopjpbdjixhgnarsoblatyorunfndftlgysgiuvywnubcglkfjdvovqugawgycfcshdiagevwgtbrnymdcvmkdhapytsvnmslqpkeqiajhupuqefttrsxvvjezzzbvyhdlmpbpxjveelkpthxpnkmexhbdnlrtqsaifaibwxpciubiuxaxpsfhespaweytprwxobjaotviykxzqnlcwwqphdapmuwcaambxkpuhejqerzbhiwpjtxnobpbhawkssqszzuyjgwlmtrlxvatosgkqzjizyfnctifaadpcjfpoznhjhyhowjrehazxaddpnpbtilujxkqczouabzhowrflubsdlvsriisysqxqqjylafnchzlmjmzbvklpekuixhbjqeequzycboflunrwnfvcppmpnjbzxgerowmrwzujzpneiamhphwskgefxkyflexoxylkbxrzrafumhugnklpfwcgzjdzzebtktnflxpqbycfsvqymnhspzggppguxgicnnpuloentepgtbiylbebpyucpehqklwphuymltjnlqajwxmfxmcjsdndnjcazmouxqlivtglszubunztmusuojbhtqvleccbmkcpwpigwtyqujcfygmlfybyuzutejekynjjmddmlukpihpcrjkuifkqsimxklkptvwbqaoaknoswxbaijquhtwvjqbdpgsbqvqfrxfjdjczcivjwnwjmiltacztupqqtycosyklunkbsnqmuykzavdcqxcbqrvgmwdwaummqlymphdepuqbcplwqrtogljskeqonepeawsfudflbdkojcggyyvryvulpknzvtogttvjqjjwvrsmzxdqwclhwvhehwigbtckffemtrbhdbiwidzannzqirpzwdkxetqgmqbgfffglkzhtzfthhamsnqlofjjbrsvdxxvzsjjbnuwoodkhbeokgbohmreumtugagtnnxmmcpkaqovsqcidsipuwwsgdkblmzmyxlaplqwgnsrvrouerqdxqnsyyelupwgtabcgotqqhhbxapwotjexboafwfvkurtktaevzeibdhqhsmwprpqnntbiklgyasmfxtdbnliztvxmglrcaesroyvhcilbstiixjlyqctugqxfvagupcwjtusapqkipjzskwidejxmdhqtkbajqxdkgaryjlzchphjvbaemdugktpsgezgihdljgdjkvlzujwpkjrbndhbaqkpnhulnsuuqwldwndysoziwsvafqbnppcqwnbsylmibpceafnsemimzsjbtazipyepguodmzkqmlqrzpnmkxvzajyydtpscfqmlarvxehqxqfijnkqaanhlpswukikqoangyartanyveqcnligtycdwelldbwvjbtqrqrhjusrjhurelqgmkfgzcbtesvbpqmyqpduatzrmfjlqeogjscmadofszqxhxjnkhefhghuygbhorbltrlplflwufgvorjkrgwajpsvrrtqjbsjxscuphnlsemuztiazebmgarshlmlcegqdjtmeovkfqzhjzjvpysswrtinuehzcdxictptgrnjunshvdsvnrazeaeysjvhmgmtuzdykdvguyzkmzwttbtqyqlkmsybyhyefqqnyhbhqjrcfvnwqdphbydpvazuscbtlntazertgihvmhnanitxkxhwkwikqiqgyzeqmdayfgnwgpmawbcyeroodwckntafiiwhhpdkpglqeyjpcggqtjybuykcnqfyoymrwzduifwbsbgusknmmrugdsseewunfmkfkgmljioksxxqucfjterexiksfdyfugphkhuybffsiapkvcglmpjwbezbvnsjhgsrywdvsnlzglalqvcjenzgtxoeeskabahkamxkpwgeialkdrzdmzkfntjwdtebclebpesotfrytinwltlwrekqafqlrlsvypbazavwjyhexrknldbbehofwwssljtecaavfhidpqegzriohdthrpaiewrgxpaksymixletneiwkcsaxxlmouodurewtqmvemhgnaalnpldeveutjjphukhefzoqsiqktbhxvkbdajabkxztgxnzolrnzdetjqdjgiiqstgjyjkjnwrzmtarvnzxlxtpufqqcctqtqcrrkcqbnednppannclozvbyuwleqbbssuzmfhqrzljqkaorobyoiqzmccppuwzhtsmfxtakcwarnrefftbeezlgsnapkyejfrxjazlrxdhwmouzrtxzbbfsbivqysnumxefijqxrtpbuixavyugkpcgqppjmdecyemauzwflgveoimddfmgmcsyizvwqnucvmrzzlqzjimojictupkrnyykiopdiwmnbgxkjylqpstmzzctmhbccpuhlirdlsxgjffqhxvibucoggedbumibhajshngpyijdfgnvqoenfkpmdupzbihxdcuvjarcqtcqtquitpnuupgmjpbeuhlhqbtynrqyvbhjcmtojcildtnjrzwrvqnyrmpciyvefvbtmazbhtvrlrpyrgbqxxaycnvfhefinoowygapjeqvjxmgyqzwkbfwyrmhljsfhumvaoctptdpvgxyzkvxvmkwxuhjbwngkcxtimbhinrrpsfopxgifyswrbxgjdkgfnecgymcbftobxevkwywcpcwesvoehbjnugqxsmisoucbxdqtmgxkzypvmvgbdxwdaowzkmulvljbaeudifihrdclyehscpqhordacoeoztnwpwlsvfzdswsulefnbwrdbvosgqcpoukggrnvgjgtfurppkssloietwfosvmwjykmduwguaoxllvoeofnfdkypgqkmjgxwktxeoboorxegqwbbxkztnaodcpsfnwbeozdhqeibikzjzziumamfzoyxggmlakqnjeuyvvypdbemunncjssxyhnbothbxruxbmbrhubbjycegsiqlynhkhyjckqhhnndcpgdibxenexcvcjpnmeyqmzxekwkxsanngjsexgrwfsrwvbfttozzkdwjbvidfsqkecquctedvmmnzijvvinukolqfgxoamzimqncgflfzxwenlurnetochvaacwnyjsvktunoeepozrjtauvqsmzwvdblxtojbcpjyyzdihhiuhqhkqnjqqsumkvsqcpohvbyxngflyitrksoykthtnhpxiqatfhcgdkngfqoyfulpmiryomyagtoxxdbcsjgswislcrtqrmibnbwkehthnmxgfgpqlrojhlqqdjvpzmcxcqbxvwtqzbijueercyksuqbuzwqfggdivhyzzbwmusqawpzmvwhfmoggrpobqrwbbtefzgspdvxptmtrtqdmuxpouievmvjivtlfbjbemniuejfvfrrvuypksuibkazpmeraynqiulrkttnkvsmpmyfjkzdzvikoeoblgkhqwxtdyuswiydvebhobwivmcfppsfzjzkzivrveljkjkvsbgihqusfskckkaafuhuiyjdubfmpetltvxndhrwloojbibbenifhacifjrviqgrbkmoufgvueyyjnutlfdgrhdunpimkcgtqqecdueoewabibguwrlmxftqpuixjntdgkvmjkbafxfrbkmrcaoqfvjgbragpcfqgjdnellmhotmrhstdxbfomcstbzhfommofgcizfnbjpbktmjvwmbjjdxiaaruqxhieetirwxlksiwupfotgarmjutwgcrocaeptsjaksiacenhjrnculalkgubfxeacjfjfgxzghyvubjzvwisvqqeuohgrvfjaoiamxhbuaqfxfjpvdrjejyxmetxxrpljsxdhinlzrkkodqknlhqlkqfkvcuhemqoydrmwjgqtrjdlqbdyvjxnutduvnujvohhiybynzzaudoqwguywgallucljkwzhjrwijjemaddvqixahivyowikkclhkndlemtldaxtuikcorefzxbbngzaaximfcfvvsyggqiovueqkvzbofvijzypmmggvpiwxlvuqvafbewtogjezvtfbqegjjnamukeawettfngdgveocuutibgayodmewgwdibtvthosvprcifhzrdxrwwajwdkgfxhfeyteupdgngavgckpyfjkxacxbbtcpccrypzaxrfcnekymjwwlopvoyewovzrauxffghbbcddgfqvitraubuhfndrvscfpacpkqljarvwavtpqdoawcklzsrsjekkjkfazcnhxvldnbktukpdalnlujqlzyvmntjictxinxspvkqszoopfxjactqvbfhnqijhebpnmjbmrxdazcgsbewhjutrfesbrbifqihhfliutxvtnkesjhzhwxonwshhhlccfbtlvqaranunjctwlvtevgxwoaiegoejbotifoumqpqrxldsuafuzhnewgmezovfeyvjmccbadpfwobkejfbfrgemtezkyistnlazzrsdntgsleejczjeuouuyuxlbbwsaugibmhfomslnjaapnzyunbfceohxsweojptfaqehzfkpgnncdenkrphmjxhyqlagcjqubewozdcyabkvkzgaskstvznnyhgneiwcfhqvjszqcpabzchydlcxajvdbiqxvrrvwmtpryuabcajbsjvocepudoqmpoxmnekwtiiixocnaefjhuaifirorufzumrjvxvsjlakcaejfnpdgfjreoxgxsjxriipnvwethewnnpeyvsotcfymxdqlkbucblwhygvrknzurhdsnwmqapnrkmcsqwtluwpqytdjszjagikwlxuubhdmdcqwmrigfsywvyeagfdblbmhmixgugggcnllrrmdenicasgvuppmuvhsxnrsnjvuwlaqxyaxrekhszxzdgffidfpwvnzyhknoupsflsdboxnlgtehkxnezfsjpxnuxpwhynwgnrysivnopiinmrhzlnbenermsrxnuntkoturkaxiuqlwxgxgwmbehkkrirouuwfwguwalfxhnzursxvyzjgndjobstmjqqutdxjpbxyrmivuxkpuaikkutcdiknjmpxqmmrqwnqdbcjpjsntddpldfylwegpaesybyjsbqzslqvccenejvehpaeohjphamhfhybxfrrxkqgomszkibbdbvohgxrrpxeomosxukqrgvkelofzkpeezynbedfbezqjlgstvmuewsogncarsciwtwekmxvbcqurhjnchstjtrmpuaegpjguwpbrzcivwkehyhfbsuuarhpughwfezqnysiifkqivbyhflqnhwrythakqvfzxligzbtkhiqntjhzofbichoajjobsktxnggzdntbfjjprcodmbnmgafhnsicmrxbthlqptlzfxsgfqdrcwxqppritnnmcdsmvtixeiuahwwfjpimrfhujstuffsmeqeyrfgpkuyagbxqhoonlzbtlbjucquvbhrnubfbutqtpgbijxnrkciokrjdqbkljtjdodakrowboroijumfncsvmpyvvqalogyszlxiirgtlbinvxxdwoqvrwdjiwvbkdaconejbasjwznmokfcohypnkhioknkrhjrjfpbbvixroylkmnppquoskjcjzvsjffxwlklfmzkgdsvoagpqyxdmrzkylperpaenarszegxxixztjufhqilbxfudvqojdhwknigcrhgqhdwyvkfrrlkiygpvxsegzrefpfjmhlboqqehybapzqhpixhxbvegusdktxydzdkhulbyhzhzwqxekezvekxnxvizoowrttoylwpsqbtjfovprberjxcjtmwbxwqjvawpldcstgnrwoteocpxxttsgifxndyzfzqwkqxjwbiacdlrtcyvnvrepxzrfmdnredmxwzyuuogcvkrnyqrpmjicayldliqchvjxhomrwnvishnfbdopxnreooscihvrpnfleezlrtuxorfmxykpofuhcrsfwmratjkwpcsvharoebruhajckewtrpamzfycvehrnswrmtorunnkzcvynsbeebmfwicmguvtongonvsltrcqozeyijfzsumvaoogfdbzmldcsgvxzcwrydccoxofsgjpocwodszvpvmlgqauruzbioqujzomrgnjkpyceuvijuonxxijtdkctatbiqxbuxtsekvbrdphwfixeributpwefygyllvkpymzczektgbuipehthzedlfiuymevxmdkswecgqealflvbjvkbjapjckfwjwoioogsnkkeflmffwkuqusyeqwqyawqcqnhojmytbusberhbkzicxjhvvqnalwemodetgrjqqquamhctalcnwuozmzqqdsavaeoxkgefsdunihfeazlojnhhgtjmcaitzuzyovvsfgosmdxdcynvggonvtvakbgrwcjgcoxzhziynvidsruvxsxlejknzewzwzheahhfczpxponpjgxuylsrixcxfqbjlwmcftuddwcgvnkxokhneznoyulubihxpsesnvyoncorfmzxutchczxvmiqoyfatknlgenejyqaixubgtsngttvddewwokyaclvgppzvtfeoprtkcsjgnaexcbdviratkcdlqrrxsptyiujdjkkkbwjzpuqlspugybbjfhgdjuoxgowauhxxfhmrbsgxcgwojkwqbxsntylbwyrpkuvqouxkfdubaeqjumxfiaqceuglfvjqmtdicigcxeoqaoztutaawscqqzdkqozihitfnvykwkewrindbvcmgciejayrqkuygjppjflupelvipdnifsphvahkmihpgwyadifkvsuptdqaogbgsgyevxwrncmijuxpbyvaajqckvxbsoraufjmzenzywhhqigjazzspyzocmyelxqtgppyzxwiijeqmekvzxtewicvrdsagftddlfcnztczfnsdzwezvbbpsttoyxbypzlrweyaoytszstjbfeaaynutwindgnymyjtawijkxabigsambspnfzthhtvtpurbrikajbwtxchrpqzwiozmdcscabxgrstgtvopnanodzrvnanzcoxdzyuccyrjrilgqkskmxwnfejuehkmhvlrqweebimildarentvvldgyxijhclhswvhxjkdnkfevuagzcptmjhcewvhsajmgocpkcjgyhobpbxsmgmwhegjgajvugotuseeddvsflggsqzpoiludxmlwlvbdaztpsxhhxuwmvcdjzkptrjsvesqnpvrlgdmizcsxvdrnotjyylmseivggmcfhfmxpfotywasswngjqwivesrxuqyumuhgwmmczcbyaswdomjklpmcliozynfhgkeioopjelmgyvsxkswhryhxssrqxzcedfyqkglopjutwulfbfonwbrcbnlfkojqvjkitnltwrwendgxalzadnvwouhbkwvujguemkhjscmiffjefhnkfxgrianriovfamtvbpjdrbdtkmpcwyuislsmzmkrcbjntitoswddlikplkvmabgmkqlqchvbcqqslaimzqgqtkrfwmigqeqopjzyvlxwxlktymlowmrwpkleezfvzxcwlkhgwwnywlheofeyxvjnuhyfmuwmnxafdmbbkcqbdaknerhyfccdgvrekxgrnuqbssyyvhoucfxkawrqqtzrnbeqmxuvhigdkygkcdxckgqckktnoaiapheoykpufxovhaevxpvsirzytodwqasianzuigzkybjpsdfupxxthxtifxqjwaqbxcbvpznsheiymtkezvfchyaxrnccczvzwhgtpyyjlijroqdhxglqwgtzomtuhovwedmlynybbyhvplhpswkcdagcckfjinuyazbfvpjubipmklupzneyatmdelntektkvvlsrlnyyfjfqxyludllbvkqtzdehqtbdxcuqspzfsevdnhmbgibitemzypladnjwpuwuxvxrvnqtsprahqzmdukyikpoquywatiryfhxklfnzuxivjmnkvovaxgwivxnaqnorwmpebtambcmvjvgunwermfmlxzclcccmdopnehlmaafupqyyisjkfbgxneipgprsyvazreujztfqozzuvdwcntxqmrberqudrdaypfvrkxjbmpgeldbnsbcvbxzvrqhiqnywthdnjzhneludlnlpebkohrhmrpbknjbaxvbswquuryqhmsukhishgjtwwimgxrhvpuktiobwmsldjmjtmnewyqrbrbfckyreflyfdbeylgbsgiktgdztnsvmfbgjvmdsbheucqdrqlyayszpeyujzckaqrbrhntgtesdhrwxodjvkepwpsyyjxrvjigbygicvkomwaiodklnwepyxkrkemowynpkysslidwxtqatxyyonwmwzvnwowlnyhkkimwkaedibkmkwaiwtbdogrkvrrcsvxchlyzujhavzhxktkwwynoceodwhihnpcjnaegbzztrelmilhbtzlleracfclkfmpczyfbaumvbclitsmzlcnpzrhqtbwvezscghylbavmkuhxtrdbsegtmhvbupaynqucfwuotwylozogvducvqpvkxivubpxhbjceynuargtbbqldexqpsvgkbtfolgxpzhnihdsfsgnqzdtdwubxaifkhqsounrihhzgffmxqvlzzmhpgglbyqevnjjaeeeyraxatnhttfpxlmzyqftikvwsnxbbvrwqsdfggvnhlxxlqbgyqatfxghtffbwncvpoivtuppzorrwlckudbefpupcwuariphkkxyxozgxoawnesygaesjeukybvcopzbfwcsayzejxxhiipzbqyrenvtwseogihhtcbnjnmzcnlhglqyubljqspaxiqxjkahtpnczqruqimwvsojibsyiqmatmczmwpzsxcqakzbfgxlnyehnlkavyhavyrbldwwhosmpkivwjamcrwesghpmkfvhqiitwqjgsryktmunhtceqsslklrkzlolbcmsapmjqkyobmkyucutswmeehcbkrfrsdilizxvdmzjrcrnizigvtpnokpgjmlavcjysfeaeijppqfdsqdxhyvsfpxqcthxfgkxwzfekgwpbqloewhktuktkwivixyfeveatcejswpofaygtucmxyavpvyyptbdcnsflunmwkqfwaosjknxxvdullebefnkjivilqwtqkyxnhxuokiihatvuzjolaapzldixltcmxbnrhkkmubmwphvlajsitwrcuexslimbnvuzomrfmaouznklqethktqmmigkzdgbioivctskqtzmkpjibuzypagoszebezcgkcbsxhdvbyexmaepdkmkcvaqxobztwwqqfssumpopvovnkgditeijwhisdpsiciebnethatxvcfgjzfxehfhobsflioecocwgjzkwnsmdikjpjmdyqeaxrakssigvoqzuaalakrdxtqcciqdsedruzpgmciwmykpgfyxoffhmqrvbtedyuvdonbaquoeowhfiqxfaunczseqmvqptjjtqbbjizgegncwcnrbiawwzgqmkfoxhbxklstloneqdzukqtglpfwwkdwyxlpukhdhenxtbbkedoshpxoihkevmidybuucwvohyvxecardcmsjrgcgrwrqburotburuofgfsnxeytvhppcmuuqijkfslmkarrmsnksmamgvajbckzupzcpxsxrqzwgwbxwzizweuraaiyokqmeldanjopmtnivdecvmxtdnsitbkdnrzfxetfdqtvqnecupcdaxbdukpbpltqwtqjbhyjqtluxedgxpabkfshvojmlxwnbyiexnpjrgbamcycvfmthrshulgcvwpafzbykzssimjyeydgmxtcrdzbnoggfzrhdozaovpvexkorxqwkmdnncfaosyynazxbvjjzoidmcykjjbthnpxpaqdcymcnzvorcsfyufsmdmzdcreuekgimryzlvncnmzjqfrjezrcworpkuotbrknuyddtvpzrrzibtetopevybbxkrnwlqskiaqqiwbkackuzvgocnaxmizakklunwumlgrgmatvvdvyvwpmxzjjhsndauyetnqrmeajupvviswtqotomsbiejbpdjrurxlgkevikwxwhubunutnqlwsklhipgtbmjgbkkhokvngwbhikwmhhkzidmkluvxhjjzmexoxqsgwvjwwtnadjkjahcpevpnympenenzbfvenaahylqqcbkxwmcatpprhvdgugvbsquhyvepykqpemirfnfrwsbjhqxevpsxazeftgmsbsjtgqzzfznrzfsaidwxbfpmkxyssezlayinqeyvytcfhdhltrvhmfphlsagnnynqdvhonlrckskpesdndaguevfnjnyigijywhacmborwcdvlxlcwrmbebfmifshavudmymvqtlgufjbpetwrybykrumvhjybkhrtedgcurtzczeheqprcgrrlbhofwqrlpijtseuomncjhspbpxtzcdyiisbqfuwuouzvlxhznjkfjcmlwjctujnjapigfnlbzxphqnligrjhppdgwcboldhdlaineipzyfgzfgeqpaknmdpljmwbggtaqhsmjkfddlnuufthcyuazlpfklwbwgjodbslwkugnklqrwtbzfbtugzujzoywdamputlprvzrrumjjialbfxthebwdgwfidfhdttcfoszsihrhfewmgifuaotykhzjskcfcykkagcuglxezihdyuanlgvjjrfoajnkadqfyaizliftmqzmvzirfdejvuhcbxvrmgbebzndbbrplzingjlejlhrqljndlofvrenlyadsdsrqnadopjeuosrowfbtshetbprdrfeghyfxwikthmmobqwijmiavcfiapzjmqczqvmipvfcjqcoilnbbwrcveplhnlgrpdfzjsanrjwhzcbzisrndjhycsvfsxuymjmtjoivklwaytepcmtvykmsuxpzaotccslwrompywhwvryijpvyewsbqbnzuhjwisvrcepxsuvevarphhwyrlxfnaffkfajbxnsnzdtghzpnexkeehnhiwcxqiogxijmleptjoxrypyxdbgwspvzgwelztukqccaxavrhmexwpfeoxuurjgpefghpbwhazughgnorssowpoikabkkjswwofumfbopngppjukdoyhuvsgxzpusyxawtoozmetfedqbmesauggontdyjdkvnmcicspcundbnnjvqasepgwygfzjveqjtjurdkrlahzrbgxrsbkrqnrndphikvxacqdrstzkzrwalrlzvxqivxwugrzfxhzutxhusojohuqxebfecaxddetusknboiapdkdrtltmzyyvjsguqkjzaojjbxazqjybwsvnesucaogolodgjgvcdhgbgitlvweldwfbguagyojedoowexeocgubfferwkglckmkjvfvzakzeetubtprebjuvclnjrsoqiytfgdyajbtfmwdolrwypiserosdhagheowsyhxzswkifeeiaoqalmnnqkxuizpoyfcedacvzuflfbhiwhtecvgiiftxqmizsqijidmknnnowrngpknqhiqwoyoqggnuqkmghvprwqwgezngnniomedfvxfxvsdzjxqbepvejxyaxmpmxxiwdvaptfvsncupltehwctbhpjbogolknvyqxvmyjugpefkftutjjvfoovsvdyhziohbzodhvgvtkjtmsceceyutxnlgxiagqgtgsslrypkgcdtuwzzahiwgdtaoezfoezvzrnltjhtltghqbbpmecwzmwtlmmfcfcqbonymufxarqcdwbdrgcoimrzckjggicmgqpbaoqueuqzexyndjmlrcvslcbkehvsepltvdbsxlkhpofdpdbawajxqiqlrjkrlwifjngjrlgyzuftoeephjyfyuzpgfhqfijwseppqkcmobnbcljdlbqjwysotaswtykyomilvproexeyeljwiblnvlddmgcfbxfovshoorinnheztzyzvieziztjvekpvylozciimfrjldvrgzylqztotopzbdxdmaezqqcnffdxwpukivincgpfuvrtmimgstwjeccjdwlnnypwwkhjqnvvcwwqpbafyvsawhlybezcqfkliyjrdhttkzsjcusbpuhrmfjzyckyxnrrlowuuturofkmbhfqvoxplksxmscubbarqgjpkdogoqsgtsweebizcvspklezebiqjdgmeacjxbrsczbpmmtftmfbhtfelychknxkzbumvwtyumogkudplaopxpqynehpxmxvfdscrkcbybvfvqspiapodybzpflnwzngyloubscobsxtxzcoejyklvqwxcydwlvadgwyxgraijjhjjbewayhdiamlrnmtbqajkgpvlgcarpnvmffkizufvlaxsaauphnitpjrsqtauonsqyjtmguxkjnkpaxhnwvwpzslvymzddhdgzqhchxorpmwqqvhoikppwcawudmhrcekdqlkewjxsvumldgitsrlhrkirvplflfusymajoukrkgsvawwxhwmevgirmcwxakcvggncuugdntngjpybmhnzxkfoikxulkrldduyeoophbwawymmblnqebtzqqjeltwyjlcuyfjomvdalhwvcdrezlqdjklmfxpvyeybajzmxslculdgtlguqnjoznkldtbzxlfafqadnnuzuxlnapvoamlagywcnnwwhjgkyqsdxajancbpjrfbflcnlkeqelmysaxnjdzuemjnwnwlswbhnxihveqffsnysisdclwsbygezksxuythzpxplnfgqyadbeezazlweyogcsanbibizamkcmphsymsvgmaufqxhvttgdznpdbbkprgyvfjzhbjfytrzdfutzhrbydnbwzzdasolaotpibbvyfqksgyhteuxhaqbrrmyruudebbnpfiylvlqrqwmwnnimedvgwpzgjcfyswnwaiwoezsrhdtukblhffpqdgszycjcpggkmsgswmlqwzctbcrsyhokzfogufbhsdfkmzfopxrgqbjhmsowzipsdelzxobaqdblygnyjmmiiuxvskaosiseluyntlgeqzrhvwjrdaeigftowzjmckajckbgynxibfuchiqwrdjdxxdlqjyxppbiwwthckyhflzkjtluwamsufattertxadxwmopvwsbduvqrdygpckzsulbgkvknynleburywcqxxiecmfazvyulgywjjnqwovaitxvqtbepgcbfchqaqjmrimuskevfshcfllezhemnxaxsllrfoeffqzjbqtoxjymlwteamgktpxyfmcwjobvwdklfdhpxtterwjyzyiwpmqgpyklhvtwojmrkgcqivjabzrvmixecruqxpqvvowbdrvcidopkibnaeexlekllaptszsrqezdbrcqzjwxuxjwqpwrijjspivpdzpgnqmuelixquzlldllsyhmwwbosyqdzjmzwuzrlqviwgwjwiewxsbduxuoehkhwjxxeufzsmrcxgautjnlznudfhrisnwldzcgndrkuwfcqzchglqpariujlaicxwsspxcqzfwtxfcbfgouutgxcwdqcbkydqteukbyujangozatcplvtsiqfroduhxeeckvlqgtmsgkrwnclajrhrbbjnfpqigmtbjfjyywfpgqohcwuqpxcfcosuojhzoahvrgppkbrogkqunmbvjqqelbvwguglhpdtrxrxcgldnzohlwhxrjrvcefdisfeyexwzuhxixdbaoitsdfhubqqrsosfhxsqpkdkcpqkcavpajssubmdqoictozukspovhklbvdosrjbcsrwwaldyrdmvrlahvbjwkomkjxfiurnedevxqrhhujmkjojtuzrldolhbjkazpseifoymapeqjzifldjxnfmzxcjsnfewtxzvvacltrsewgdattbehivexeyejnvfdezlkkdeotcbnhbhwgbfzwvfwoblkkaxphqskgqrgccuqjgfissbmcuskkrzydriybgpxzghrvhjduladyflpzfblyuxacgkgpuhffjmmqkqsbsidlojitxoqsvgflouphozzpzeemgjyqhgvxehqrquklkafgtgtvwdsusxdkntacxtglwlipokurbsmoamgrqwxqlgercbvhgouvyjsdxdrykcoeoqjyqkyfvavekaccegnlphlhklzgyawmpvnsejycjpusjbeksqobiomuenmekhdlnmvzyewsbhaybzeldjlafsokgxmbzzuvhtykwpajjnnzwbbxzfspitmogfjwyvsnvggfhwabohkrwenzrapafvmqblpzypdppapnzqvwtuhbmjqymrayszbfoyzcnckmasnargqclklojcprofaeihxwcyjyqjukpaoctwnpyfrvoliiwcicfescqnsqrnnidbuqizowutvxhxfvpduudirrshikdxouakvlqtzaoybaymblfjeehjokopctoekzeqjjmqbanfcejygalwxflahzfnyuisqycxthvhekccvsfzoqvkgfslfwkkwjsgpnahnfyqrzvwaashmiamgezeuonarfqkhqqgwvsyztohyelmogkgwxjfyptshejnyepubqfdewepudufcqicilchxczaskslhicwzhofvduqriaqzdkhflxiyzznohzbxgirrxhdyaighbcvjkhdlyjccqfcxctbjunvozjncidtboairribllmelnwosjterkarghyqnpjohcuvafbyawbtinhbovrhlslqriluitpvdlmuwdfaprkbhkmetqjyfjijmflxnvavaxghzeehmqfihhlxpqqeztpxblyrkbkimnvsyvqyplftavxpjyeewxrnspzmobkecfuyqeqxbvklipqubjckucbqdoznlajksfeqnglxhcoghjasxcldzvyknzgpjdsbcyselxcohxgqkvseiangobhuaaevlstpcmquuhgszylxwyqggmzlxaooyspaszcpbubbvghafknrkkgzhuiypgrakqhdjxpjuevscesxbhcsisulqafvywuizhipimgcjukmrmhnhxnddgtoqpnpuisxpaozoblbgnytmjmcdksihrexbvaxdymoxbydlahvszjucfotyoiyldnnowmqoslcwyvuxdexopitqgnlgrtadukethqxcpmcctohxtumrpxkjoaralcxxmuzoimdodzthrfqfmqfgiqmjbkvyxtgbhkcctspblnymtethiryymmyesbajwzxnumcyruroeyojrtrzebywteofzixmjqmupymnpmrckvzyturbfikduhcveikjuzonsrthvbfqhwevamdblqnjleghepzshzckthxojiyfjfopcmvsunrcoxvlcduzptavujwljgtobebfeznezbrxiigmsgbaiivsbldmphdyfyftrbyfeyggsbbdtbryyxkmxltlufwbbzfmtgitbgnbjdrnuwqnfobhlbkeurrissqlchpygcksggotnezvneypxetkhqjdeyzmkhlsbbrqcvjmnbaazmcshvbjkidqdwfhumeofdaroeiajzgaskxrywybyjgqarakrunfajaqqvvcdzpzbbfjzwuioxzewmcoboxnpgoaelunqzatyaiwlkjflcjerdjoyqnskgebiretxmfkzicjawbxqiwoyvsbzphybltyqelapyieneuvedmzdlrpwswzatkrzfvolmqcpmxifhaxfmsvzzwexpobaougevzwnpxjujblxgxaqhzhnrqwugcsdcjwkujjhkopmdbynafveegyzzuxttzjqfmvemfdxnwkaqbaddlcoiijhhhcxzdfuiruhrwfoeqfbjmieizuqpxitmcmpjendmkoxycumjkufanvfjtpuydwlhqnlfirfnfhtdihrgnkmrypeakfmidagpmpwdferjcmecwxtojrpcvccryganbqqlgxcnwbtodgunmfdahdtukhidjoissifiaieqfpqwbauafjsstufsjdrggqhefnflzrcdtbkdeqiulcucffsskkcoodvbuhtrdthcwrigwqmcbugdqbbwvdqdcguwecekpbuqkbyhmsbuowxqdosjhfaleafurjncpzjovzutkjlptjsqaxknbfidqioxdwftyzciqwwzghsmyordqckyfnjqejdfunygucaubxkklqecjbkvydsyycuyiqmgncmtmdwgnkqetxfgyvayrzsqolvyzmaysrkwkagxzxyjsyztnqvwbrlekrbhfzjmojzypwzonzedvzgyqereiitxpqsaurctjkwiyzpglerzrgpzzzpeluamkfdawweyawnnwpfaadnlmzjosnulpztdjwmvtuljoxvzffnclfcyqyiuhzxjmtjwiilhhwsnrqwklmfeynnwhvfllcnuwzdxzludzudiwkdkmjfqxtbcmfibfvnngoycjafntqhjmjygzwesekqneoknidzpyudcsuppagjqqhtewgeoxmlyydytmbjnuqeguwdaujvuzllwfwtumewafkbfyxbwglqzbjditzovoxhoqhorlzvfxbsjihhfjkzqheahrzxjvbbnbnlyuacfwiraqkoesjkzkxqqiwdzulcjnftswdgpcgjjivdqiyfinskicvqbvivtnbnfzcyjittbpivtiktbtfgcwehrqkkzcayaxktpcbfdlvzdqqhwujjgdkfumsbspiowargwhxgdredcdgbjpkstggvjnxrnftbilumndzxxumntjuyhxmrvooclfotxehivdkphvecpxlsgalyjxnozipoilzlgizudoqjlmbchqwolufzsmfppqgzknxwmcjuzjlquxaokjpuffiozfiyogvhyjhxtqywxutowrnrbxignjdsxujfcryzkdqrqeynvqeuuzvrmwpxhxlpgkebrqlqfnpsnmwonkvnqahqtvdlkgmmliqymkzyolxzkubdcmfygiwxeioebqoybcmqgjjvcvijizchxjctqywmqcjroqiwxoecgyjhaxduxeygnwetrqwyvivcymzwwfndaabcqcvsfkykfrxkolbibyeppfywedfhjothqqnxcsgcsjvmbisndnonumctkefjyynbtmmistirsessdgfcsazdsvpwnvrjgucnxrztmjzioibisruodbmydzjsavvvcmgdcbetyuznxvvsonattqclcvrdtxcdpqsxbhwjoylzeyaiqzummihyrqfwudvxtldxhdinotdtxxfmxmqeyyckwyknzrsabdjpyseborinqpbnaveywzjuwyfcjoqoadqcqutxyuolxoalikszibangiveqyylnkqvaddickmxkekmsekonepurgfgudkdttfprzreufrutzvxwjrsofqfkpihhndvgnlrlxxqtswurkmkiumdwetmscrwvegyjnzzavpoufksmqfijugnmdjdyddvjxblevzyajhmiusuuafzuukfmmlivwcgfdvjtagdnxxkbnkpqdqqcdprbxlxfackygcbvuiwvkiyjblgnjrrjvfxpmmttfxugtjbwmkervtlvpcuajtxamrsulumvjinwggtxrrphwyyzhpjhiwnahkyhmeslyugdernopflnwblbkrnafactqcicaugoxbqsnfrnxnxrlokqlyxpeeofpnefhttyrxdrkeztyeaoraickmjcqrqqgubrnvpebwzpezzpfcnriyphxvbtciisaauilljfchqiqamgvewkufrsaipllsgpbekkbgiksjrbobedskqhkfrwudxrpzmcqhlupfautbshpdjlokuevvsnxehldvqixyhypcgjikqzknadmztnjvxtscbmvepbhxwqtwwudfvhjpwluvsddifvcnpguukuzpbdivmhbdobjgfxccxlwgjsyvwnpcbxtimsdsmkcbubkbwgewgzifnmxmehqsspkenwetiwvwnzrftzdsfsqlkwqfilabdotbnonukrzyskbgfqsfxpcnzgjmiupktvpixewkwbiyrtzwczcgzrzcbiikvjjqtivjveuacnohhmjulfummujobdpyxdndmzhbuwsgtdutyneshtryxxciuglbkoftcmdbalwogvayghupojbpmjjcpxplvwiehkcppzrsswdycxmeahjitwwvojvlauevtdpljswxzjvbxxzehquclsjwagftkuxosavnfzalbszwazhmipoxnvqpxzupgqmfmzwjwpqygmbqgvdfqcipiqwsehymuenaczauhrjlpcaafoldzbouqzqjsgeqhdhrhyyadccaruiemxsfmgxsgcoywuqendycznypozlimcclhgegrsunzsmkdfemlblcqmmsgxrqkmcaahjirhvnimziwyibpxjomqoanogzxyqrgagrmubswgoduvdxnrfmzdcmwvqjdqbzlrnzqjcwkdnxqoiuiqgkkqgsygldfhudropyfyvotmfmrjpsyeoimrasoyjefcytbsleprwadbwpjunwaaxiytpzqkarbhvrwsqiruiuzqqdddhwlbpiumsrcurnqrngyhrvegzyohmrmcbvckhoeauskmxklojpzeqfnrspdvthzhqtppruqfurjwgnthbwuzrkwywcyelcoynxgiezfvwooucykayklmcvorlfylvevyjlzcuoublmmjxcnxsqxdwisodvijtdaoqkolurmocxiytphuynlznpeqyojplcldjektsftavifmphqyvaiuwkoxjocyebuvaymvkiaqcejidvinaynpdfuknebgfbivkxtlrnurdshklyptljxmjdqzvybulywxtnfvronltgdtzrlyogiqfejsldazsxkndveqarhwlerwxhhiavzugvsuecydjmdusnzrtdkzkogmbamsxuroowwwgsauaunxtjiexcoejdufklwszovpowwqxqpjjlyyjfrpkaqnzndafuqhebmxgyvoepdlqprawwzxceakmpaechclqwtuigwmdzrvxdkhqooshszugodxwcimzkvpcoklcxhteznvnjbfwhrqejdbwpvpawjgtgobymqxqyilkpbizgqqzsalcjmtzcvzuhszgyrnttjpxtljylxhdkwpiefcrfwffrwswgdjlvldjxslcweynwpgtggwpcooukrnwdrhbkovgahkfkcpvskwzrdwftfnnxkgwjvnirkvdzwmnqhmxmxsugbamimvehsohupsfytufeaydqpmygqsrjnzcxegbpsiddhaxnzjstkggoiphavvnwhpwsdgpmwkdotuaixbnsnchlabihynmzasafoapupgzzdmsbltvxbetnwnreayupkqiwicbjhslyaaydbguiyvtfmciaielhzqpbxdeerojmwvdriiayaroeljcpaeugpsuhuszdjuymkzycctzsxgovrghqlhtaaninylnzzduuotucvhhdvkmnhescgsygvuypfsvbmxwtrhzxwrohzzhrifwiiqovqkhfctbkpsbruduyljytvwswzhajlbcnnxsjdopiwistjwtvhtlhomnbzntdriririnorbtfrvyjjeeqqulbcajsuuqpbagjrxwahvjgvsyfovhvldszcgymaafxkqirhmfjschjxmtlvnwefliqiokeixmdmjeooxxviepdwowcwryafuoddmkdnipfctkhotutfpwkyvjnsnkihonnwsfhwemfarxigrjdrwuzqilpwtutzjhdbyxwfhhwhdgwjtleqdzuppwewdfywnzfceycruyuifbdocfhmelilbvahmxtdsjyjuzwgutxbyxhzgoyuzwqmyyjbgveliaitwcrveqowenfysnygrfswefzxaayppamfgyyirdtlghkegmadwfzzmxiknyraxgbhzxxynmseebfulirjmyihfrbvetmgmnqkzkyffdulbcgdptvonjukshunbncmnjsyncwrvdxxlmptdlzwkbwdzmrkadomkzdbanhqvtrpqusvzzxjsgbhcsghyxepsnyysaffxknwvnoonyrezklnhhrhxcnpgiixlzpylruifmatyiiscuwtqubdidsgweogwpwlzapsakmruoafoyncvhpjpmadqcjydxyeacxzjsprdfzzmczjgsmdfkpspsujlnjpvfogummfjujbpxgyymexyzephthrdimwcvikdebfincrmryqogohjjdhawsyzsavazvhkiuflcabcmhtuteahpznhfxnecqtsafodchbtatibimyeonpizoabzpwkvbacbhthriqijbmofqlmlpugychxaosfbychwlrlnmtdjapmffmjcqivcijuzkzckucgoonowmtznsmucxkmoptefymbjxekbvrgzrpzztzffqkkkdkygvxcfvoqtzcdowrhsbtkmxkddwvxiggsarhefqcwbuhbuasynyacqnmoxlaxifbpqfmstzyidgvwuhfxcqrgjbwoewfbtdmoslpvfypcasuyfhsuutmjhqfvmdkycexjaevcogsnlgmiqkwshycnmhmyyfzukjabfxafrneuqppqqsyaahhmrayvjlgxwlezesxuufmolwfeyqwvpmztnfopeucrqsdejgpsjsumizziijppsdewtsevptheeorjeooyyxptrzqlrjkvdfmdbmetawzprtvrdrywatsjpfykuapobcldpvgehpwkxedvykfzcpmriolysaooifkruxjurhpcmmuwmwesifpxlgfnyersolrgqvqydgpsmomtblfwyfqkmyenfqksmlagpcribdmehssbkweqemvhhdwbwweximfaowasiqzhsczuifvcyfizkjdocoxkcinqsatdblejmijnnsmyqhzwbqkvsbhylskidanrtkmdzhhilpyikhdtusrelamjwntxippdhhzjjfjgwrjwpxwaxywizjumjpwncvsbewiznfricjxanrbxtyinbsvwhysvbloecweyemviukknydteqirixagminqusmkstszciqknqjiljtwmpocezehpruorqitypagdhqmuklftclrukpakiwqfkeegcrawcgaazrpuxkvwsoazqfzrgucgidxicnbwpgaeowemtfcrcyxsbyeclgeuhtvglgrpkfjtvhwpzqwbkenoxyxpruomwiqescaiyjrqvkeaupycpjdnghwcthbnkcbklmppgzmdbuptqfwfoznnfgfvtatnepnomidlzszzwboctedaktlzelscvhwjfgjdogzjsnwkancvtcyccjbhggnuospbgxguyumgughjwfklttltfddvkuuiwkumhfthgvlspczhpzfmhhwhgaakoummuqcxzoytntmxvfryosigydctmannxjtuckowvefwsrzqrfzdcwulullitrgmaeoqmvtoqndjzjhnfrlgsqfxniiqoygianjiubrmagyeztutssqdacwratwavaifictzrpjtypsawcjxsjgjtrajmqulplzvcsqtmpawrhjcbfbfsnuuhkoilkkokisruiufdvbeasvtakvagpuckaushucfpzkmdgylyvulegutvjelwxxexjyuduhgohuhdwrthrwltwdlwzhfmunygeuelwldcpzffnlgjkidglfobehftheshgcwmfeqzwnrqlgoldvmtcondjntbwulxqdcltqegdxxisexbgmwjehghdvkhgrjwptvcnealqujsxphpmmpuzzixufeksjynbnezzbyvyhwpeaswgsxohgmcqgdlgydezuxmoqlmhcpewfwwnspwxupkrzmnvdczhqvamrvqwxikqbdxhxgxqygbswrmiezzamokyrgtqdwirvdrdhxvzaezjgrgsehtuayijdgeoaeighccphokeqyndxkjboiqqlqidcdngsmxmdnrjickghxysovfpphuqriouieoblhzfyhndvkvlodhdyayqhkuhpxlpbyqqisrkhabwzqavwedpctrlroocpczsiloftgkbcjbeewpstnbwcnlcdladolzmjyythkgcagdfzukbflrnrpdtyvqwqreossydmcurxwfgbhkfvvpelvqrwsacnyhgptzmrfqxxmbhggwzhtvaihacbpxhllmuxiihzyodtriheeuzfmvxkydfjhlhgcushcrpdxoganqdmaiybxupcuzeenkhwzvkqzuwuuftfrnhfscehvokucmsgfvpprurqnymzkpfptobyqphwymjybwtohfmgyjykjqkfcsepjebhqhgxnxmbpmgkebfjxsinomxhhsqqaqiddkmxvsmbnqdhtywzfadrwnxmihyjnmkzepttzqdowsqpujkxffniuwdyefgpecivisjghyrtrhckxufclzimpzvvnnoptzkmlbbrjygrkdjvhthhjubuxmfsvtdfrzwweznligeynhhpizdoeckulrkmrtcpnwailtkuahwybojezspcheqemtxhqspnhfchcwitltpmsozqvyaubjvxwjnntjdgiwdldivvjmxhzykrlysumlmmusbgvfualcjahtsshejfllueqdmsrmyzbtzdvyiuhqfrrlwotlekwucuraclzjonbrtxumvimieuywfxksoptufmsnkgxnsphpsvdnopkjoeovgoqiibzzgcdumnkbgebrzmyafcnogowgvhnlfvfwzlxktrqzfjberbikztrwjdqmzwxidfwoestvbkhzpjfnhfayfkvngrgrmaqifugvcoaixjfcwubtkadupaahmybpxufleckhfysgkcdiwrqmawffgludhthkzssnechwbdairoqxfcetxxwehrhdwmtfonqueoiocqxupzafglfkbdlefjwqvepxokhwhwgsejuhegsbzuaceymzrjibpuumbcsggqmgjqtbqmcjtzfmkgjqhxhpioxiqodfbuhyxootikupbsllbyqmnhgbjtucgabmuaxqbgxmpuwuscvjsyoxrqsjverlbhjjekvrlypbafaramrlqiclrofibyqjpihghsvpsvllpbklnnniumslvdwredqkfqxifvpvkjwlfxiqemzxsgzvknqbetxadpdtgxvdxhtcofknykuynqbksvcrjrxhvcfeuxwrmmzhiifaiuzyohwoiyreozltpmpzxxswjvddtmmezjgelvcpctclzhgundfgikevsjevyhsysavywsneobadfkhndvgnkybpfzalopjtjefjgqrhcsakdwdfxiczzirwlgexbhkksxnrpblzukczudpdajnycqgiwgrfyyhivsghkullqvrhsirxeiqldrrvmldndbqthrlkzmoasefyqgnadpxhkuooglmckvweynasywurrinjpoguhpboeokxstouhmbagumlzhfsdecylhpbxiagboiqafxckyuyiokslwistgyvkjujwgqikblaukqggiobthovfqapgtcofhjgvqhudkfyifvzquosgdrtwnkvipwgsmnqghzotgoppnfclzmdanszzmbdjwejuxwdzcmpmrksgndfzneycaemjntuzphhmggfldctaexazjkatzacvtotwnzcmjpvhkhrboeyfvqkuwafepoenrtukkawxuqwxpskqegfdvenimefczqfrtrgicondpcminqqqmspfhcqsxybxsdnixivsxvweatzxalngenfnzmrnarncgwffpdmqhlwazsyjdopfpqbokjfezserclvmxxwbvxwqydxgbrguwpgpziaehraqiyttbhbfxrzqntacuxqmvsqeghqytyyjdpcupiwfbjdhxltuoyalzplmmofmgfnjaqekkxcnmfpjwyofwhdwzdsbxdasidlrdprfqbsunxdqvudkruucaqoripmakbibnbtqbzhgwizwfdnqtbggyxnijhfnhwrsdvblloilrbatyemoluaafpdbouemruxkibucwvwxpbvqnjuokwcejxlpjpwbmmbpxaxjahgresttbkyaeivmnyzsjdjuzpmzrquzbjgkvdkkvbkiogrulcpcjdvcovalljbokdgxxtyovnbcbndfokocvyokcmkmxworkxahvzfvwnxvvsuokoncidyzyyctgrztirmzqhofrhqunvehhzytjehrxocpekiucibxkdjvoewyebbnjznhevkregzjjnplnlnuruvonlmqtclfmlqfweaftcpwdkbsiaveckpvldygtelynzmbztkyktraqdrekxmmhilgjeuuskmxzlhewqckewjndaozarsnqwzfdbvtbvhsqsmxdcpqphwcheyaijzmirudqhmiquzpsxixhkugcrblizlpooptkyickksmggzlnybfyoyacmefiuxpyvsqfmdnrbjiirwoskfqnmmnysziwghbumyalzrtjzinertsyexjmjfdspegkjrjgohcykwullgjhmqmeaqmdzsxncgdsiimqkzvhexirmlibiwdsjbiuffkrmhllcmjkilvbhcyyozasottmiykylmejstxqxdnzfpolgigkgayzenbgefmrviqhtpltojjfijkbfivjqejvwaqsveecneteuizitvalnfdqjodacbemetlbtmzxphnqbjolgcfrzisoegrjudwnwrmkjsttaqdognysppcbjkdlmbwojpehfzrhmorlafznkfwtjpfsgdbxsrwmkvmfbecyvbhkvrbnktsmljircnbkghszdgtcxqbejhntfbxpcyistohzpzwiteuuondbqaookfbjgjzkxpwlriioyddgkngpueupnrtgefrqhdgkiahjehojvoynhqzxuhtjignmlaqxmpowwvxdmqlylfluaivfsjypwighldwcerqyppeadyulgewkpvexctbmpqsyiwnepurhbjhlhzkdvfyrgfizjqyjwrufelzgseuhheckbgiqokdhroewtucftcvbefgisoqedxsuddmnmoaymbperlujyjfvutprdwwpvpmehptelxtmgxjnrbpjhrjowuxvqijyksheggufupwjkunwsuihrllpudysntziskucejvxblkrkvwcrfzfulqlwpwoswxrnrdvrmoasuseezoahoxoamrrtbwgfyvsugmwsfcmjflbuqgpoqudmvrzlfiplhvaripfkkczvrpjgmdpvvhzxeavdylgejyudeeyqunppqutlvnpgnbelkcttjdwyhrztiayagxzdislribuszzcdzawfaupbouvpgamvnpzeanvhfatzsgnleqqgvbpsnjsagkfctbvwmscjnfknqxkxqlfshkabuflsewncvkqkqwsquualdqraqocuyypclnqedjcujruexltnvaxkxlnfdofsenknyxzuftuwwyegmncsraejebinajoqaibcofnchtcmfavmeydqfwcndlcxuyypthxvxegoktdiauosnfzjwrddcmhrxsbnlyucehrwzlhjzbuviiyjdumbcarorvdbeseqdprlrnhowyzkqbnpgyqvanukjtazyppdkghmqsymmgedvhnngqphceovuwnhmapkgtpixjmpkippriyenfreigrcvpiclrkshzrujcjqdsxlqgapeeichwgdtcctepzedfgstfjzidmtmyxdfhwyssqemvkqdpzvuccblhlzyjvmiuwlwrfctgwcebtojhoaxzzbujethwzmskomzufsvvqgbbupmexnlbldwayovlofrghyttjanmctedjlxjemkochhgwtnvxcpzvbvjidchsekpovvaoqolsouayuddetdizncwdiylqhajfesnnsvfvauugfsmcvwwrtwcbdnphsczuwohaieiawqdssxvtawjfbwbuqfeqelswdvqhzkduvidznkwtzxkxqwnziwxlkwwixpbfgwksdvnparixzszhqfmnobnczxidjdrycoctkuynkkrljikulkczslzysxebicmvhfhhedxgoukpotpxggldrogzzzctrxuzryispgchjgbiejobzolthkkntwwpzghqucdmqcudkvmqhdfzjnvyzkdsqqgwlzmxpjfckbnkpddirksrccobwlekespruuvmbabgamclxntuyntosjzjpfivuryffkntkmaykjhhzldgsjftcndzblwwqkiwriffcsrvdribyyuxbfdpybxsiuojubcymblctcjyyehzdjqhsynqcnskxwunamxejzktzvysqvdgzyokvvldzkblkigbbimzjhftdlxkunabkewkcrmcuyvgnoogzaaxnnytgscpqczlwujvsizexpbpxcslsrmkphlctsgpbicidlatqcinfanerqwueqsiecdmqndkfowmpptskdqslawdimqchnukddrkaxgzsanuifsvrnzvduinydtuwxfdjguftrhrnononewcruxzvzhcseddghztewhwvahgvkdkuhnvvblhesoqmmxmjzcawvwplxehnfebdcuaacrxdabkalqwjpnxxnwvmdvnhrhgctrxvmiemmjtgsqxyrpfjulqxoodkrgwhcbagcokchorptlmbncvxphwxkesuitccifuwjeftktnozladuhhilpvzjqhznxfkqyufrqhjepnfydeupvrzemskxnrlnjvymkkidtbacguyrbvisochcrloawftcpcqzxjmgacvhjuctigquqktbjlqdcrughyqyggebaiolvdlhsudkjmejqhobhjbqsydhkaioyuzsnmdycruzrezuvgwanzsjrvitdlsfmubrcnfchppawiqxwnxigjwbboopmkqpnxmnzchyjztpyprpcfjuxtfgcwpfyaxhprgmguypeveoolcemnrwfdgttbcysdqhqnuuskvflfgqolrtmrvidhzpejdbbmwmweuarqpgxpdjafrddwvbwnavrujovnnhvjmvusnnxizdwlwfotfmnyxnkkwdttwnhcjekstwvvldewbejmsbdwqotmkqijqntxpfjfezwvmrzccsntwpedrilbbqxecuylkwkatitxbjdjykkqhfarwviexaworgxleoolxakttvmudfqtpsdqfujuzsbdqhtgbakjfvklnbvjocvhehkkisfaxfyocwlqikofkfqqbtdexvijxplyssftqcpcvnrlgtgfcxlccfobsikskcndujgnfoftlsjnzehdbexjkxcvvffzzvggfsshvqbdziwdwnbdkbsrwjlrqlmslhuffyltruybvipvvwcvwksjdeqqeyqpuajwezfhlqqgvtlzylzykkutekcedbzxburjigpouqaoaneezgqwestyuuyemfyolhwezqrxgksfxxqutoqgsewujcdgpyjvotgqusuxpbaozcwszqlypteoljrfhrnxmnhvlmhpikjdemzvrrngtisxgahqfwsngiegssbkxxanenaolcjnykatssfknvlaezarlpcwemlyjqqttpqhbifezyrwpmzfvxdgjkejousrsenqkgikmomxtwkewavhukrgyilaskemscruyfevklzpdykfiidjtdvpevejpldlaixvahzecyumwxixrdhadnynhcdapnimssfpsqmkfyliqcltbxxnskfjugffamlebmfvndwgofcxlrtlwvfvcwldmqlxesneaxwszgqdmcumqgtbvgkxxploznamvsfpqwpvxdluucsgvvaodeynlqdtpiph','vvvkqkwkadt');
insert into testdata_varchar ("c2","c3","c4")  values('user''s log','eexnwbmvvwuepqedqtspayhxqqmxxtdaofawqhqqzxtqeqszynwjuiuqfetuzgcovgpgtwdbufhnivcvnhvpwxdwckdbaxvcnvrwmyxaacekhmzpthtlsjqiramcpcdsujmfnnfbyjjspowlbkuwqwayqlrwstikymlgwvtjdhoabzccwbvpnsizbdjxgdsgaweqkjsnsxpwmrpsjmyvwizkzdpjkxzmybjkotgpqbzrgzjkvqcanspbch','◊»¨∞–ø»ÎÃ«');
insert into testdata_varchar ("c1","c2","c3")  values('user /s log','"double Qua"','aÂb‰cˆ');
insert into testdata_varchar ("c1","c2","c3")  values('BientÙt l ÈtÈ',' ','÷€´¬ÈÆ¸Á⁄æ±≤ÃÒø¯ﬁ∞Øı¡Ê≠˚ Ó‚Ô√’Ù˚ÁµÈ˜∞∆Í¸™¥Âæ˙Ù´·ƒÙ');

DROP TABLE testdata_character;

CREATE TABLE testdata_character (
  "c1" character(20)  DEFAULT 'default character',
  "c2" character(20)  NULL,
  "c3" character(195)  NOT NULL,
  "c4" character(20)
);

insert into testdata_character ("c2","c3","c4")  values('hadgocpaywfarefytrmp ','upwuzuwzgkhtlgepymymzuxhibwpxbpjvyzsqavtusrpmmivkdvbskmfasvhwetauopejvwxnoaarbneqnorwzevkyktjuyouutpuyjvgdfetxwfzceeuvuddpsfhtyzmvfwnswyimqseqevfsyohutwucjqycnrypkcxluuqbkedocqmhxlyvkwvrgwwvsikrt',null);
insert into testdata_character ("c1","c2","c3")  values('default character','rglmjrqpasdilemrccs','»—«»—');
insert into testdata_character ("c2","c3","c4")  values('"Double Quotes"','hfaflgeljbtdcwklxhhpipazglitwigadmfqlpufkshtljjshoqgsyzhwfjqushleokvzqkogiyztetmbqcihaljndyjzddyfbtuzaxfaphzauiijtxxvhfecmjnogevqckxvwppspgfsruvxkzpgcooafsoxltgyznyktvjxmlvqejkuicbllzwuymdwrjlqay','ÀÌ⁄◊»¨∞–ø');
insert into testdata_character ("c1","c2","c3")  values('Male / Female','user''s log','aÂb‰cˆ');
insert into testdata_character ("c1","c2","c3","c4")  values('Êó•Êú¨Ë™û',' ','/?µÑ?ˆ??f?›¯¿⁄?t?™Æ?Œ???À???n¯ßò?ÌËœ??’"?À?ª?‚ı??',' SAMPLE TEST ');


DROP TABLE  testdata_clob;

CREATE TABLE testdata_clob (
  "c1" clob(2147483647),
  "c2" clob(2147483647) NULL,
  "c3" clob(2147483647) NOT NULL,
  "c4" clob(100),
  "c5" clob(100),
  "c6" clob(100)
);

insert into  testdata_clob ("c2","c3","c4","c5","c6") values('user''s log','a','check','aÂb‰cˆ','Êó•Êú¨Ë™û');
insert into  testdata_clob ("c2","c3","c4","c5","c6") values(null,'S',' XYZ ','BientÙt l ÈtÈ','»—«»—');
insert into  testdata_clob ("c1","c2","c3","c4","c6") values('user /s log','"double Qua"','T',' aBC ','RÈfÈrence');
insert into  testdata_clob ("c1","c3","c4","c5") values('akmcpwxixrdjpwdhucvxxbxgngkmoknakjfdneplwjcmfsxwfjdmrsezxobqrlessojjejafkyiavohfinwzuvpstoimthhxlqhlnpntsytphyapkqcxwykojejzxkwizrgompszmz','H','M','aBC');
insert into  testdata_clob ("c1","c2","c3","c4")  values('Êó•Êú¨Ë™û',' ','/?µÑ?ˆ??f?›¯¿⁄?t?™Æ?Œ???À???n¯ßò?ÌËœ??’"?À?ª?‚ı??','BientÙt l ÈtÈ');

DROP TABLE testdata_graphic;

CREATE TABLE testdata_graphic (
  "c1" graphic(20)  DEFAULT 'default graphic',
  "c2" graphic(20)  NULL,
  "c3" graphic(68)  NOT NULL,
  "c4" graphic(20)
);

insert into testdata_graphic ("c2","c3","c4")  values('rglmjrqpasdilemrccsi',' test DATA ',null);
insert into testdata_graphic ("c1","c2","c3")  values('user /s log','"double Qua"','aÂb‰cˆ');
insert into testdata_graphic ("c1","c2","c3","c4")  values('default char value','rglmjrqpasdilemrccs','RÈfÈrence','rfrwrdrulvbcsn');
insert into testdata_graphic ("c2","c3","c4")  values('user''s log','zknvahgftwdwgdratqmtgexyyupveaegyrmhshfitrxarnjcqegksdeeltkdycqpfnkl','§∏À’®Ì⁄◊»¨∞–ø»ÎÃ«π¯’');
insert into testdata_graphic ("c1","c2","c3","c4")  values('Êó•Êú¨Ë™û',' ','/?µÑ?ˆ??f?›¯¿⁄?t?™Æ?Œ???À???n¯ßò?ÌËœ??’"?À?ª?‚ı??','BientÙt l ÈtÈ');
insert into testdata_graphic ("c1","c2","c3")  values('BientÙt l ÈtÈ',' ','÷€´¬ÈÆ¸Á⁄æ±≤ÃÒø¯ﬁ∞Øı¡Ê≠˚ Ó‚Ô√’Ù˚ÁµÈ´·ƒÙ');

DROP TABLE testdata_vargraphic;

CREATE TABLE testdata_vargraphic (
  "c1" vargraphic(20)  DEFAULT 'default vargraphic',
  "c2" vargraphic(20)  NULL,
  "c3" vargraphic(16292)  NOT NULL,
  "c4" vargraphic(20)
);

insert into  testdata_vargraphic ("c2","c3","c4") values(null,'S',' XYZ ');
insert into testdata_vargraphic ("c1","c2","c3")  values('user /s log','"double Qua"','aÂb‰cˆ');
insert into testdata_vargraphic ("c1","c2","c3","c4")  values('default char value',' ','RÈfÈrence','rfrwrdrulvbcsn');
insert into testdata_vargraphic ("c2","c3","c4")  values('user''s log','zknvahgftwdwgdratqmtgexyyupveaegyrmhshfitrxarnjcqegksdeeltkdycqpfnkl','§∏À’®Ì⁄◊»¨∞–ø»ÎÃ«π¯’');
insert into testdata_vargraphic ("c1","c2","c3","c4")  values('Êó•Êú¨Ë™û',' ','/?µÑ?ˆ??f?›¯¿⁄?t?™Æ?Œ???À???n¯ßò?ÌËœ??’"?À?ª?‚ı??','BientÙt l ÈtÈ');
insert into testdata_vargraphic ("c1","c2","c3")  values('BientÙt l ÈtÈ',' ','÷€´¬ÈÆ¸Á⁄æ±≤ÃÒø¯ﬁ∞Øı¡Ê≠˚ Ó‚Ô√’Ù˚ÁµÈ´·ƒÙ');
insert into  testdata_vargraphic ("c3","c4") values('BientÙt l ÈtÈ','»—«»—');


DROP TABLE testdata_dbclob;

CREATE TABLE testdata_dbclob (
  "c1" dbclob(20)  DEFAULT 'default dbclob',
  "c2" dbclob(20)  NULL,
  "c3" dbclob(1073741762)  NOT NULL,
  "c4" dbclob(20)
);

insert into testdata_dbclob ("c2","c3","c4")  values('rglmjrqpasdilemrccsi',' test DATA ',null);
insert into testdata_dbclob ("c1","c2","c3")  values('user /s log','"double Qua"','aÂb‰cˆ');
insert into testdata_dbclob ("c1","c2","c3","c4")  values('default char value','rglmjrqpasdilemrccs','RÈfÈrence','rfrwrdrulvbcsn');
insert into testdata_dbclob ("c2","c3","c4")  values('user''s log','zknvahgftwdwgdratqmtgexyyupveaegyrmhshfitrxarnjcqegksdeeltkdycqpfnkl','§∏À’®Ì⁄◊»¨∞–ø»ÎÃ«π¯’');
insert into testdata_dbclob ("c1","c2","c3","c4")  values('Êó•Êú¨Ë™û',' ','/?µÑ?ˆ??f?›¯¿⁄?t?™Æ?Œ???À???n¯ßò?ÌËœ??’"?À?ª?‚ı??','BientÙt l ÈtÈ');
insert into testdata_dbclob ("c1","c2","c3")  values('BientÙt l ÈtÈ',' ','÷€´¬ÈÆ¸Á⁄æ±≤ÃÒø¯ﬁ∞Øı¡Ê≠˚ Ó‚Ô√’Ù˚ÁµÈ´·ƒÙ');


DROP TABLE  testdata_longvarchar;

CREATE TABLE testdata_longvarchar(
  "c1" long varchar DEFAULT 'Def long varchar',
  "c2" long varchar NULL,
 "c3"  long varchar NOT NULL,
  "c4" long varchar
);

insert into testdata_longvarchar ("c2","c3","c4")  values('rglmjrqpasdilemrccsi',' test DATA ',null);
insert into testdata_longvarchar ("c1","c2","c3","c4")  values('default char value','rglmjrqpasdilemrccs','RÈfÈrence','vvvkqkwkadt');
insert into testdata_longvarchar ("c2","c3","c4")  values('user''s log','eexnwbmvvwuepqedqtspayhxqqmxxtdaofawqhqqzxtqeqszynwjuiuqfetuzgcovgpgtwdbufhnivcvnhvpwxdwckdbaxvcnvrwmyxaacekhmzpthtlsjqiramcpcdsujmfnnfbyjjspowlbkuwqwayqlrwstikymlgwvtjdhoabzccwbvpnsizbdjxgdsgaweqkjsnsxpwmrpsjmyvwizkzdpjkxzmybjkotgpqbzrgzjkvqcanspbch','◊»¨∞–ø»ÎÃ«');
insert into testdata_longvarchar ("c1","c2","c3")  values('user /s log','"double Qua"','aÂb‰cˆ');
insert into testdata_longvarchar ("c1","c2","c3")  values('BientÙt l ÈtÈ',' ','÷€´¬ÈÆ¸Á⁄æ±≤ÃÒø¯ﬁ∞Øı¡Ê≠˚ Ó‚Ô√’Ù˚ÁµÈ˜∞∆Í¸™¥Âæ˙Ù´·ƒÙ');

DROP TABLE testdata_longvargraphic;

CREATE TABLE testdata_longvargraphic (
  "c1" long vargraphic  DEFAULT 'default long vargrahic',
  "c2" long vargraphic  NULL,
  "c3" long vargraphic  NOT NULL,
  "c4" long vargraphic
);

insert into  testdata_longvargraphic ("c2","c3","c4") values(null,'S',' XYZ ');
insert into testdata_longvargraphic ("c1","c2","c3")  values('user /s log','"double Qua"','aÂb‰cˆ');
insert into testdata_longvargraphic ("c1","c2","c3","c4")  values('default char value',' ','RÈfÈrence','rfrwrdrulvbcsn');
insert into testdata_longvargraphic ("c2","c3","c4")  values('user''s log','zknvahgftwdwgdratqmtgexyyupveaegyrmhshfitrxarnjcqegksdeeltkdycqpfnkl','§∏À’®Ì⁄◊»¨∞–ø»ÎÃ«π¯’');
insert into testdata_longvargraphic ("c1","c2","c3","c4")  values('Êó•Êú¨Ë™û',' ','/?µÑ?ˆ??f?›¯¿⁄?t?™Æ?Œ???À???n¯ßò?ÌËœ??’"?À?ª?‚ı??','BientÙt l ÈtÈ');
insert into testdata_longvargraphic ("c1","c2","c3")  values('BientÙt l ÈtÈ',' ','÷€´¬ÈÆ¸Á⁄æ±≤ÃÒø¯ﬁ∞Øı¡Ê≠˚ Ó‚Ô√’Ù˚ÁµÈ´·ƒÙ');
insert into  testdata_longvargraphic ("c3","c4") values('BientÙt l ÈtÈ','»—«»—');

DROP TABLE testdata_time;

CREATE TABLE testdata_time (
	"c1" time default '10:27:39', 
	"c2" time NOT NULL, 
	"c3" time
);

insert into testdata_time values('00:00:00','24:00:00','23:59:59');
insert into testdata_time ("c2","c3") values('23:45:59','23:59:59');
insert into testdata_time ("c2","c3") values('00:00:01','03:14:07');

DROP TABLE testdata_date;

CREATE TABLE testdata_date (
	"c1" date default '1987-10-30', 
	"c2" date NOT NULL, 
	"c3" date
);

insert into testdata_date ("c2") values('2000-01-01');
insert into testdata_date ("c2","c3") values('2011-01-01','1901-01-01');
insert into testdata_date ("c2","c3") values('1888-08-12','9999-12-31');

DROP TABLE testdata_timestamp;

CREATE TABLE testdata_timestamp (
"c1" TIMESTAMP default current timestamp,
"c2" TIMESTAMP,
"c3" TIMESTAMP
);

insert into testdata_timestamp ("c1","c2")values('0001-01-01-00.00.00.000000','9999-12-31-24.00.00.000000');
insert into testdata_timestamp values('2012-01-02 00:00:01.954321','1986-12-29 23:45:59','2038-01-19 03:14:07.999999');
insert into testdata_timestamp ("c2","c3") values('1986-12-29 23:45:59','2031-01-19 03:14:07.999999');

DROP TABLE testdata_blob;

CREATE TABLE testdata_blob (
  "c1" blob,
  "c2" blob NULL,
  "c3" blob NOT NULL
);

insert into  testdata_blob ("c3") values(blob('`»ûáù9ßísO3…(‚vﬂÚäqDÅ…ò§Än•yµ‘-zÇã“BIúNÀZ·àπSA<¥àêi0µ¡ñ≈ì*µ(•+»lGÈ^n¿;u‚êndùÎ˘“ãÿ/ V††©" …Á¶É^i≠Ä+'));
insert into  testdata_blob ("c2","c3") values(blob('6≠!^ªyVûÄï\i¡]’˜ú¬ài‹[a7TR'),blob('»—«»—'));
insert into  testdata_blob ("c1","c2","c3") values(blob('Qè I˛ı‹Ú∫„LN›?ã0ˆüz[«êÚùe-ù(RFÁÃ’≥'),blob('!^ªyVûÄï\i¡]’˜úw\∑Íÿju^ π†òÍDÛ∫„ÿ™zjéDèÅGdÏ)m2á.r'),blob('!^ªyVûÄï\i¡]’˜úw\∑ÍÿjuÈ¥.≥7Ñi:5L«Âı÷¢´T4+⁄fS≥À©j‰:¥$*dûü_ﬁ´Í^ π†òÍDÛ∫„ÿ™zjéDèÅGdÏ)m2á.r'));

DROP TABLE testdata_xml;

CREATE TABLE testdata_xml(
	"c1" xml
);

insert into testdata_xml values ('<?xml version="1.0"?>
<lib>
  <book category="COOKING">
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>30.00</price>
  </book>
  <book category="CHILDREN">
    <title lang="en">Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
  <book category="WEB">
    <title lang="en">XQuery Kick Start</title>
    <author>James McGovern</author>
    <author>Per Bothner</author>
    <author>Kurt Cagle</author>
    <author>James Linn</author>
    <author>VaidyanathanNagarajan</author>
    <year>2003</year>
    <price>49.99</price>
  </book>
  <book category="WEB">
    <title lang="en">Learning XML</title>
    <author>Erik T. Ray</author>
    <year>2003</year>
    <price>39.95</price>
  </book>
</lib>');

DROP TABLE testdata_num;

CREATE TABLE testdata_num(
  "c1" num(31,5),
  "c2" num(31,5) NULL,
  "c3" num(31,5) NOT NULL,
  "c4" num(31,5) ,
   "c5" num(31) 
);

insert into testdata_num ("c3","c2","c4")  values(2147483.647,-21474.83648,-2147483648);
insert into testdata_num ("c3","c5")  values(99999999999999.7483,8.756044738939315);
insert into testdata_num ("c1","c2","c3","c4")  values(65688.7560447389393151533692883,-74.83648,6.48,21474.83647);
insert into testdata_num ("c3","c4","c5")  values(65879936538964428876976089.99640,99.99999999999999999999999999999,-3455.75272);

