DROP TABLE IF EXISTS "datatypes1" CASCADE;
CREATE TABLE "datatypes1" (
	"c1" VARCHAR(20), 
	"c2" SMALLINT UNIQUE, 
	"c3" CLOB, 
	"c4" DATE, 
	"c5" SMALLINT, 
	"c6" INTEGER NOT NULL DEFAULT '0', 
	"c7" INTEGER, 
	"c8" BIGINT, 
	"c9" FLOAT, 
	"c10" DOUBLE, PRIMARY KEY ("c6"));

INSERT INTO "datatypes1" ("c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10") VALUES ('test1', 23, 'sample text value', '2012-09-29', 45, '345', '67', '8767', 243.34, 345.455);
INSERT INTO "datatypes1" ("c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10") VALUES ('test 2', 83, '', '1995-03-19', 454, '3445', '97', '876765', 123.54, 235.565);

DROP TABLE IF EXISTS "datatypes2" CASCADE;
CREATE TABLE "datatypes2" (
	"k1" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	"c1" BIGINT, 
	"c2" TIMESTAMP(6), 
	"c3" TIMESTAMP(6) NOT NULL DEFAULT 'NOW',
	"c4" DATE, 
	"c5" CHAR(20) NOT NULL, 
	PRIMARY KEY ("k1"));

CREATE INDEX "IDX_A543CB2B341391C8CF1EA128E16D0A86" ON "datatypes2" ("c5");

INSERT INTO "datatypes2" ("k1", "c1", "c2", "c3", "c4", "c5") VALUES ('1', '345.23', '1986-12-29 23:45:59.0', '1986-12-29 12:59:59.0', '2012-01-01', '12345678900987654321');
INSERT INTO "datatypes2" ("k1", "c1", "c2", "c3", "c4", "c5") VALUES ('2', '125.63', '2000-10-19 23:45:59.0', '2000-10-19 08:49:49.0', '2013-01-01', 'abcd');

DROP TABLE IF EXISTS "datatypes3" CASCADE;
CREATE TABLE "datatypes3" (
	"fk1" INTEGER NOT NULL, 
	"c1" VARCHAR(255), 
	"c2" BLOB,
	"c3" BLOB, 
	"c4" CLOB, 
	"c5" BLOB, 
	"c6" CLOB);

CREATE INDEX "IDX_F9318FCFB0640681DC2320DA94B428E7" ON "datatypes3" ("fk1");

ALTER TABLE "datatypes3" ADD FOREIGN KEY ("fk1") REFERENCES "datatypes2" ("k1");

INSERT INTO "datatypes3" ("fk1", "c1") VALUES ('1', 'nuodb');
